### ISSUE TITLE
 meta-gir  with  Poky: Zeus(3.0) for ARM Cross Compilation facing the issue 

### ISSUE THREAD

**Issue by alexvatti** [Guacamayo/meta-gir#5]
meta-gir  with  Poky: Zeus(3.0) for ARM Cross Compilation facing the issue 

When I want to build aravis , it is depend on meta-gir 

libgirepository:   The primary package providing the consumer library for the
                      target (with the tools included in the dev sub package).

While clone the meta-gir and while doing the build facing the issues

**Comment by rossburton** [comment]
meta-gir and Poky Zeus are both very obsolete, but more importantly meta-gir isn't needed with zeus at all as gobject-introspection support is integrated into poky.
